# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  GOPATH: '$(system.defaultWorkingDirectory)'

steps:
- script: go install ka.org/sample/app
  displayName: 'Build'
- script: |
    az artifacts universal publish \
    --organization "https://dev.azure.com/kazakovas90/" \
    --feed "go-packages" --name "sampe-app" \
    --version "$(date +%Y%m%d_%H%M%S)" \
    --description "My description" \
    --path "./bin"
  displayName: 'Upload artifacts'