# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  GOPATH: '$(system.defaultWorkingDirectory)'

steps:
- script: go install ka.org/sample/app
  displayName: 'Build'
- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)/bin'
    vstsFeedPublish: 'go-packages'
    vstsFeedPackagePublish: 'sample-app'
    packagePublishDescription: 'sample golang app'